In [7]:
import numpy as np
from collections import Counter



In [3]:
def getOutputYVector(y_output_image64, numCats): # y_output_image64 is of shape (3200,64,64)  , 34 categories + -1
    result = np.zeros((len(y_output_image64), numCats), dtype=np.float32)
    cCount = None 
    for i_, img in enumerate(y_output_image64):
        cCount = Counter(img.flatten())
        if(len(np.unique(img)) == 1): #if all -1's
            result[i_][0] = 1
        else: # get the second most common thing (since -1 are going to be the most common)
            result[i_][int(cCount.most_common()[1][0])+1] = 1 # get the second value (index of 1) of most common array
    return result

In [4]:
y_output_image64 = np.random.randint(35, size = (3200,64,64), dtype = np.int16)

In [9]:
abc = getOutputYVector(y_output_image64, 36)

In [10]:
abc

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [11]:
abc.shape

(3200, 36)

In [12]:
abc[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0.], dtype=float32)

In [13]:
np.where(abc[0]==1)

(array([29]),)

In [14]:
img = y_output_image64[0]

In [15]:
cCount = Counter(img.flatten())
cCount.most_common()

[(32, 140),
 (28, 139),
 (6, 134),
 (12, 128),
 (8, 126),
 (1, 125),
 (7, 125),
 (10, 124),
 (11, 124),
 (14, 124),
 (34, 122),
 (15, 121),
 (4, 120),
 (22, 120),
 (0, 119),
 (13, 119),
 (16, 119),
 (5, 117),
 (30, 117),
 (25, 116),
 (26, 116),
 (3, 115),
 (17, 115),
 (20, 115),
 (2, 114),
 (23, 113),
 (31, 111),
 (18, 108),
 (19, 106),
 (24, 106),
 (21, 102),
 (27, 102),
 (29, 99),
 (33, 98),
 (9, 97)]